[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"

[target.arm-unknown-linux-musleabi]
linker = "arm-linux-gnueabi-gcc"

[target.arm-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-gcc"

[target.armv7-unknown-linux-musleabi]
linker = "arm-linux-gnueabi-gcc"

[target.armv7-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-gcc"
